const MOCK_PARAGRAPHS = [
  `The Winnipeg Jets' whiteout tradition is one of hockey's most striking spectacles. Unlike other teams' color-coordinated playoff crowds, this phenomenon began in 1987 as a response to the Calgary Flames' "C of Red." When the original Jets faced the Flames in the playoffs, fans spontaneously dressed in all white, creating a stunning visual effect that transformed the arena into a swirling snowstorm. The tradition persisted even after the team's relocation and was revived when the Jets returned in 2011.`,

  `The Manitoba Legislative Building hides in plain sight as one of North America's most intriguing architectural mysteries. Designed by Frank Worthington Simon in 1920, the building is actually a temple of sacred geometry and Hermetic symbolism. From the Golden Boy atop the dome to the sphinx on the roof, every measurement and symbol was carefully calculated to create perfect mathematical harmonies. Even the grand staircase's dimensions correspond to the sacred number 13, believed to have mystical significance.`,

  `Nestled in Winnipeg's Exchange District, a curious time capsule exists in the form of a defunct ghost sign. The massive Royal Crown Soaps advertisement, painted in the early 1900s, remains remarkably preserved on a brick wall. What makes it extraordinary is that the building it adorns was constructed before modern billboard regulations, making it one of the largest surviving ghost signs in North America. The sign's preservation is attributed to an adjacent building that protected it from weather for decades.`,

  `The St. Boniface Cathedral stands as a unique architectural paradox. After a devastating fire in 1968, rather than completely rebuilding the cathedral, architects chose to preserve the fire-damaged stone walls and integrate them into a new, modern church. The result is a striking combination of ancient ruins and contemporary design, where the original façade stands like a sentinel guarding the new structure behind it. It's one of the few examples worldwide of architectural preservation incorporating ruins into active use.`,

  `Hidden beneath Winnipeg's streets lies a dark reminder of Cold War paranoia: a massive fallout shelter designed to house the entire provincial government. Built in the 1960s, the bunker could support 350 people for several weeks and included a broadcast station to communicate with survivors. Today, the shelter remains largely untouched, its mysterious corridors still containing original equipment and supplies from an era when nuclear war seemed imminent.`,

  `The Winnipeg Zodiac, embedded in the floor of the Legislative Building's Pool of the Black Star, remains one of the city's most enigmatic features. This perfectly circular room was designed to create unusual acoustic effects where whispers can be heard clearly across the chamber. The zodiac symbols inlaid in the floor are arranged in a pattern that some believe channels cosmic energy. Visitors standing in the center report feeling a subtle vibration, though scientists debate its source.`,

  `Few know that Winnipeg's Assiniboine Park Zoo played a crucial role in saving the Przewalski's horse from extinction. In the 1970s, the zoo became part of an international breeding program for these last truly wild horses. The harsh Manitoba winters proved surprisingly similar to their native Mongolian steppes, making Winnipeg an ideal breeding location. The zoo's program successfully produced several foals that helped reestablish the species in the wild.`,

  `In the heart of Winnipeg's North End stands a former bank building with a peculiar claim to fame. The Merchants' Hotel, built in 1913, features one of the last functional bank vaults from the city's boom era. What makes it unique is its floor: thousands of pennies meticulously laid in a herringbone pattern, installed by a local artist in the 1970s. The copper-covered floor has oxidized over time, creating an ever-changing patina.`,

  `Winnipeg's Fort Garry Hotel harbors a ghostly secret on its second floor. Room 202 is famous for reported paranormal activity, with guests claiming to see a woman in a white dress walking through walls. Legend says she was a bride who tragically took her life in the room after her husband died in an accident. The hotel embraces its haunted reputation, though they never assign the room to unwitting guests.`,

  `The city's connection to Winnie the Pooh began in 1914 when Lieutenant Harry Colebourn bought a bear cub from a trapper for $20. Named her "Winnipeg" after his hometown, the bear became the regiment's mascot before being donated to the London Zoo. There, she caught the attention of A.A. Milne's son Christopher Robin, inspiring the beloved children's stories that would captivate millions worldwide.`,

  `Beneath the domed ceiling of the Bank of Montreal building lies a curious acoustic phenomenon. The perfectly circular main hall creates a whispering gallery effect so precise that conversations can be clearly heard across the room when standing at specific points. This architectural feature was unintentional, discovered by bank tellers who noticed they could hear private customer conversations from across the space.`,

  `The Winnipeg Art Gallery houses the world's largest collection of contemporary Inuit art, with over 13,000 pieces. But what many don't know is that beneath the gallery lies a climate-controlled vault carved into the bedrock. This underground chamber maintains perfect conditions for preserving these delicate artworks, some of which are carved from materials as fragile as whale bone and soapstone.`,

  `In the 1920s, Winnipeg's grain exchange was so significant that its telegraphed prices influenced global markets. The exchange floor in the Union Bank Tower featured a unique circular trading pit where fortunes were made and lost daily. The pit's design allowed traders to see and hear each other clearly, creating a theatrical arena of commerce that helped establish Winnipeg as the grain capital of North America.`,

  `The secret of Winnipeg's mosquito control lies in an unexpected ally: dragonflies. The city maintains special ponds designed to breed dragonflies, nature's most efficient mosquito predators. Each dragonfly can consume hundreds of mosquitoes daily, providing natural pest control. These "dragon nurseries" are carefully monitored and maintained throughout the summer months.`,

  `Hidden in plain sight, Winnipeg's water supply flows through a 157-kilometer aqueduct from Shoal Lake, completed in 1919. What makes it remarkable is that it relies entirely on gravity - no pumps required. The engineering feat was so precise that water flows downhill at just the right grade to reach the city, making it one of North America's most efficient water systems.`,

  `The Royal Canadian Mint's Winnipeg facility contains a mysterious room known as the "million-dollar cube." This perfectly square, high-security vault once held the master dies used to strike coins for dozens of countries. The room's walls are so thick that they could withstand a direct hit from a locomotive, protecting the valuable manufacturing secrets within.`,

  `Winnipeg's Tyndall stone buildings hide ancient secrets in plain sight. The limestone used in many downtown structures contains fossils from a prehistoric sea that covered Manitoba 450 million years ago. Sharp-eyed observers can spot traces of ancient marine creatures preserved in the walls of buildings like the Legislative Building and the Fort Garry Hotel.`,

  `The city's first skyscraper, the Union Trust Building, was built with a curious feature: a rooftop garden designed to grow vegetables for the building's restaurant. In 1904, this was revolutionary urban farming, predating modern rooftop garden trends by over a century. Though no longer active, the infrastructure for this visionary project still remains on the roof.`,

  `Winnipeg's Cornish Library floats on rafts. Built on riverbank clay in 1915, engineers designed the building to rest on wooden rafts that would allow it to shift without cracking as the unstable soil moved. This innovative solution has kept the library intact for over a century, while many neighboring buildings suffered structural damage from the shifting ground.`,

  `The famous Burton Cummings Theatre began life in 1907 as a theater for vaudeville performances. What few know is that beneath the stage lies an elaborate system of trap doors and mechanical lifts designed for magic shows. These Victorian-era special effects mechanisms remain largely intact, though unused, making it one of the last surviving examples of early theatrical technology in North America.`,
]

export default MOCK_PARAGRAPHS
